36 Fixing Postsync bug

diff --git a/manifests/java-hello-app/templates/argocd-postsync.yaml b/manifests/java-hello-app/templates/argocd-postsync.yaml
--- a/manifests/java-hello-app/templates/argocd-postsync.yaml
+++ b/manifests/java-hello-app/templates/argocd-postsync.yaml
@@ -61,22 +61,51 @@ spec:
 
 
               ### NEW TEST
+              # echo "Starting command" && \
+              # echo "GITHUB_TOKEN: ${ARGO_POSTSYNC_GITHUB_TOKEN}" && \
+              # echo "TARGET_ENV: ${ARGO_POSTSYNC_TARGET_ENV}" && \
+              # #JSON_PAYLOAD="{\"ref\":\"workflow-automation\",\"inputs\":{\"target-env\":\"${ARGO_POSTSYNC_TARGET_ENV}\"}}" && \
+              # # Remove any trailing newlines from JSON_PAYLOAD
+              # #JSON_PAYLOAD=$(echo $JSON_PAYLOAD | tr -d '\n') && \
+              # #echo "${JSON_PAYLOAD}" > payload.json && \
+              # #echo "Contents of payload.json:" && \
+              # #cat payload.json && \
+              # #echo "Hexdump of payload.json:" && \
+              # #hexdump -C payload.json && \
+              # curl -L -X POST -H "Accept: application/vnd.github+json" \
+              #   -H "Authorization: Bearer ${ARGO_POSTSYNC_GITHUB_TOKEN}" \
+              #   -H "X-GitHub-Api-Version: 2022-11-28" \
+              #   https://api.github.com/repos/Irembo/irembopay-api-integration-tests/actions/workflows/release.yaml/dispatches \
+              #   -d "{\"ref\":\"workflow-automation\",\"inputs\":{\"target-env\":\"${ARGO_POSTSYNC_TARGET_ENV}\"}}" && \
+              # echo "Done initiating pipeline" && \
+              # sleep 10 && \
+              # echo "Command execution complete"
+
+              ### NEWER TEST
               echo "Starting command" && \
               echo "GITHUB_TOKEN: ${ARGO_POSTSYNC_GITHUB_TOKEN}" && \
               echo "TARGET_ENV: ${ARGO_POSTSYNC_TARGET_ENV}" && \
-              #JSON_PAYLOAD="{\"ref\":\"workflow-automation\",\"inputs\":{\"target-env\":\"${ARGO_POSTSYNC_TARGET_ENV}\"}}" && \
+              JSON_PAYLOAD="{\"ref\":\"workflow-automation\",\"inputs\":{\"target_env\":\"${ARGO_POSTSYNC_TARGET_ENV}\"}}" && \
               # Remove any trailing newlines from JSON_PAYLOAD
-              #JSON_PAYLOAD=$(echo $JSON_PAYLOAD | tr -d '\n') && \
-              #echo "${JSON_PAYLOAD}" > payload.json && \
-              #echo "Contents of payload.json:" && \
-              #cat payload.json && \
-              #echo "Hexdump of payload.json:" && \
-              #hexdump -C payload.json && \
-              curl -L -X POST -H "Accept: application/vnd.github+json" \
+              JSON_PAYLOAD=$(echo $JSON_PAYLOAD | tr -d '\n') && \
+              echo "JSON_PAYLOAD: ${JSON_PAYLOAD}" > payload.json && \
+              echo "Validating JSON payload with jq:" && \
+              cat payload.json | jq . && \
+              if [ $? -ne 0 ]; then
+                echo "Invalid JSON payload"
+                exit 1
+              fi && \
+              echo "JSON payload is valid" && \
+              echo "Contents of payload.json:" && \
+              cat payload.json && \
+              echo "Hexdump of payload.json:" && \
+              hexdump -C payload.json && \
+              echo "Executing curl command:" && \
+              curl -v -L -X POST -H "Accept: application/vnd.github+json" \
                 -H "Authorization: Bearer ${ARGO_POSTSYNC_GITHUB_TOKEN}" \
                 -H "X-GitHub-Api-Version: 2022-11-28" \
                 https://api.github.com/repos/Irembo/irembopay-api-integration-tests/actions/workflows/release.yaml/dispatches \
-                -d "{\"ref\":\"workflow-automation\",\"inputs\":{\"target-env\":\"${ARGO_POSTSYNC_TARGET_ENV}\"}}" && \
+                -d @payload.json && \
               echo "Done initiating pipeline" && \
               sleep 10 && \
               echo "Command execution complete"
